server.port: 7650

endpoint-config:
  allowed-origins:
  - http://localhost:3000
  - http://localhost:5000
  - http://2.239.139.233:8762
  - http://localhost:8761
  allowed-methods:
  - HEAD
  - GET
  - PATCH
  - POST
  - PUT
  - DELETE

spring:
  application.name: service2